<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[===Application started===]]>
    </line>
    <line>
      <![CDATA[Test case iWillFailfailed]]>
    </line>
    <line>
      <![CDATA[===driver closed===]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="21133" started-at="2019-05-31T08:47:11Z" finished-at="2019-05-31T08:47:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21133" started-at="2019-05-31T08:47:11Z" finished-at="2019-05-31T08:47:33Z">
      <class name="TestCases.BoundToFail">
        <test-method status="PASS" signature="setDriver()[pri:0, instance:TestCases.BoundToFail@ea4a92b]" name="setDriver" is-config="true" duration-ms="20015" started-at="2019-05-31T14:17:11Z" finished-at="2019-05-31T14:17:31Z">
          <reporter-output>
            <line>
              <![CDATA[===Application started===]]>
            </line>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method status="FAIL" signature="iWillFail()[pri:0, instance:TestCases.BoundToFail@ea4a92b]" name="iWillFail" duration-ms="6" started-at="2019-05-31T14:17:32Z" finished-at="2019-05-31T14:17:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestCases.BoundToFail.iWillFail(BoundToFail.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case iWillFailfailed]]>
            </line>
          </reporter-output>
        </test-method> <!-- iWillFail -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:TestCases.BoundToFail@ea4a92b]" name="closeApp" is-config="true" duration-ms="732" started-at="2019-05-31T14:17:32Z" finished-at="2019-05-31T14:17:33Z">
          <reporter-output>
            <line>
              <![CDATA[===driver closed===]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- TestCases.BoundToFail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
